from pathlib import Path

APP = Path('app.py')
RUNTIME = Path('static/modules/training-task-runtime.js')
MAIN = Path('static/main.mjs')
INDEX = Path('static/index.html')
FRONTEND_TEST = Path('tests/frontend/training-task-runtime.test.mjs')
API_TEST = Path('tests/api/test_training_unified_task_overlay.py')

app = APP.read_text(encoding='utf-8')
old = '''        job.update(\n            status=mapped,\n            progress_percent=float(durable.progress),\n            task_stage=durable.stage,\n            task_status=durable.status.value,\n            current_item=durable.current_item,\n            result_ref=durable.result_ref or job.get("result_ref"),\n        )\n'''
new = '''        public_runtime = task_to_public(durable, shared_task_repository())\n        if public_runtime["status"] == "WAITING_RESOURCE":\n            mapped = "waiting"\n        job.update(\n            status=mapped,\n            progress_percent=float(durable.progress),\n            task_stage=durable.stage,\n            task_status=public_runtime["status"],\n            current_item=durable.current_item,\n            result_ref=durable.result_ref or job.get("result_ref"),\n            queue_priority=int(durable.priority),\n            priority_scheme="lower_number_first",\n            resource_queue_position=public_runtime["resource_queue_position"],\n            resource_wait_reason=public_runtime["resource_wait_reason"],\n            task_worker_id=public_runtime["worker_id"],\n            task_lease_expires_at=public_runtime["lease_expires_at"],\n        )\n'''
if app.count(old) != 1:
    raise SystemExit(f'training durable overlay anchor count={app.count(old)}')
APP.write_text(app.replace(old, new, 1), encoding='utf-8')

runtime = RUNTIME.read_text(encoding='utf-8')
anchor = '''function priorityValue(job) {\n  const raw = Number(job?.queue_priority ?? 50);\n  if (job?.priority_scheme === 'lower_number_first') return Math.max(1, Math.min(999, Number.isFinite(raw) ? raw : 50));\n  const legacy = {100: 1, 80: 20, 50: 50};\n  return legacy[raw] ?? Math.max(1, Math.min(999, 101 - (Number.isFinite(raw) ? raw : 50)));\n}\n\n'''
addition = anchor + '''function queueRuntimeMeta(job) {\n  const parts = [];\n  const position = Number(job?.resource_queue_position || 0);\n  if (position > 0 && ['queued', 'waiting'].includes(String(job?.status || ''))) parts.push(`队列第 ${position} 位`);\n  const reason = String(job?.resource_wait_reason || '').trim();\n  if (reason && job?.status === 'waiting') parts.push(reason);\n  return parts.join(' · ');\n}\n\nfunction workerRuntimeMeta(job) {\n  const worker = String(job?.task_worker_id || '').trim();\n  return worker ? `执行节点 ${worker}` : '';\n}\n\n'''
if runtime.count(anchor) != 1:
    raise SystemExit('training priority helper anchor missing')
runtime = runtime.replace(anchor, addition, 1)
old_row = '''  return `<tr data-job-id="${esc(job.id)}"><td><div class="train428-taskname"><b>${esc(job.asset_algorithm_name || job.algorithm_name || job.id)}</b><span>${esc(job.id)}</span>${job.auto_version_name ? `<em>版本 ${esc(job.auto_version_name)}</em>` : ''}</div></td><td><span class="pill ${statusClass(job.status)}">${esc(statusText(job.status))}</span><small class="queuepriority428">优先级 ${priorityValue(job)}</small></td><td><div class="train428-resource"><b>${esc(resourceName(job))}</b><span>${esc(job.framework === 'paddle' ? 'PaddleDetection' : 'Ultralytics / YOLO')}</span></div></td><td><div class="progress424"><i style="width:${percent}%"></i></div><span class="train428-progress-txt">${job.current_epoch || 0}/${esc(totalEpochs)} · ${percent.toFixed(0)}%</span></td><td>${esc(duration(job.elapsed_seconds))}</td><td>${esc(duration(job.eta_seconds))}</td><td>${esc(dateText(job.started_at || job.created_at))}</td><td><div class="row wrap">${actions(job)}</div></td></tr>`;\n'''
new_row = '''  const queueMeta = queueRuntimeMeta(job);\n  const workerMeta = workerRuntimeMeta(job);\n  return `<tr data-job-id="${esc(job.id)}"><td><div class="train428-taskname"><b>${esc(job.asset_algorithm_name || job.algorithm_name || job.id)}</b><span>${esc(job.id)}</span>${job.auto_version_name ? `<em>版本 ${esc(job.auto_version_name)}</em>` : ''}</div></td><td><span class="pill ${statusClass(job.status)}">${esc(statusText(job.status))}</span><small class="queuepriority428">优先级 ${priorityValue(job)}</small>${queueMeta ? `<small>${esc(queueMeta)}</small>` : ''}</td><td><div class="train428-resource"><b>${esc(resourceName(job))}</b><span>${esc(job.framework === 'paddle' ? 'PaddleDetection' : 'Ultralytics / YOLO')}</span>${workerMeta ? `<span>${esc(workerMeta)}</span>` : ''}</div></td><td><div class="progress424"><i style="width:${percent}%"></i></div><span class="train428-progress-txt">${job.current_epoch || 0}/${esc(totalEpochs)} · ${percent.toFixed(0)}%${job.current_item ? ` · ${esc(job.current_item)}` : ''}</span></td><td>${esc(duration(job.elapsed_seconds))}</td><td>${esc(duration(job.eta_seconds))}</td><td>${esc(dateText(job.started_at || job.created_at))}</td><td><div class="row wrap">${actions(job)}</div></td></tr>`;\n'''
if runtime.count(old_row) != 1:
    raise SystemExit('training task row anchor missing')
runtime = runtime.replace(old_row, new_row, 1)
RUNTIME.write_text(runtime, encoding='utf-8')

main = MAIN.read_text(encoding='utf-8')
if "./modules/training-task-runtime.js?v=422503" not in main:
    raise SystemExit('training runtime cache anchor missing')
MAIN.write_text(main.replace("./modules/training-task-runtime.js?v=422503", "./modules/training-task-runtime.js?v=422504", 1), encoding='utf-8')

index = INDEX.read_text(encoding='utf-8')
if '/static/main.mjs?v=42.25.90' not in index:
    raise SystemExit('main cache 42.25.90 anchor missing')
INDEX.write_text(index.replace('/static/main.mjs?v=42.25.90', '/static/main.mjs?v=42.25.91', 1), encoding='utf-8')

frontend = FRONTEND_TEST.read_text(encoding='utf-8')
frontend += '''\n\ntest('training row exposes real queue wait position reason and worker without a second request', () => {\n  const previousWindow = globalThis.window;\n  const previousDocument = globalThis.document;\n  // trainingTaskRow is pure and does not require runtime installation.\n  cleanup();\n  return import('../../static/modules/training-task-runtime.js').then(({trainingTaskRow}) => {\n    const html = trainingTaskRow({\n      id: 'wait-1', status: 'waiting', queue_priority: 1, priority_scheme: 'lower_number_first',\n      resource_queue_position: 2, resource_wait_reason: 'GPU_MEMORY_BUSY',\n      task_worker_id: 'a800-worker-01', progress_percent: 18, current_item: '准备训练环境',\n      framework: 'ultralytics', total_epochs: 30,\n    });\n    assert.match(html, /等待中/);\n    assert.match(html, /优先级 1/);\n    assert.match(html, /队列第 2 位/);\n    assert.match(html, /GPU_MEMORY_BUSY/);\n    assert.match(html, /执行节点 a800-worker-01/);\n    assert.match(html, /18% · 准备训练环境/);\n    if (previousWindow !== undefined) globalThis.window = previousWindow;\n    if (previousDocument !== undefined) globalThis.document = previousDocument;\n  });\n});\n'''
FRONTEND_TEST.write_text(frontend, encoding='utf-8')

API_TEST.write_text('''from platform_core.task_runtime import TaskKind, TaskRecord, TaskRepository\n\n\ndef test_training_job_overlay_uses_unified_resource_waiting_truth(tmp_path, monkeypatch):\n    import app as app_module\n\n    repository = TaskRepository(tmp_path / "tasks.sqlite3")\n    repository.create(TaskRecord.new(\n        "train-wait", "project-1", TaskKind.TRAINING, "payload.json", "training:gpu:0",\n        priority=7, required_capabilities=("training.ultralytics",),\n    ))\n\n    def deny(database, candidate, worker_id, token, expires_at, now):\n        return False, "GPU_MEMORY_BUSY"\n\n    assert repository.claim_next(\n        "a800-worker", [TaskKind.TRAINING], {"training.ultralytics"}, admission=deny,\n    ) is None\n    monkeypatch.setattr(app_module, "shared_task_repository", lambda: repository)\n\n    job = app_module.enrich_job_runtime("project-1", {\n        "id": "train-wait", "status": "queued", "queue_priority": 50,\n        "framework": "ultralytics",\n    })\n\n    assert job["status"] == "waiting"\n    assert job["task_status"] == "WAITING_RESOURCE"\n    assert job["queue_priority"] == 7\n    assert job["priority_scheme"] == "lower_number_first"\n    assert job["resource_queue_position"] == 1\n    assert job["resource_wait_reason"] == "GPU_MEMORY_BUSY"\n    assert job["task_worker_id"] is None\n\n\ndef test_training_job_overlay_exposes_worker_and_lease_for_running_task(tmp_path, monkeypatch):\n    import app as app_module\n\n    repository = TaskRepository(tmp_path / "tasks.sqlite3")\n    repository.create(TaskRecord.new(\n        "train-run", "project-1", TaskKind.TRAINING, "payload.json", "training:gpu:0",\n        priority=1, required_capabilities=("training.ultralytics",),\n    ))\n    lease = repository.claim_next("a800-worker-01", [TaskKind.TRAINING], {"training.ultralytics"})\n    assert lease is not None\n    repository.heartbeat("train-run", lease.lease_token, progress=18, stage="training", current_item="epoch 2/10")\n    monkeypatch.setattr(app_module, "shared_task_repository", lambda: repository)\n\n    job = app_module.enrich_job_runtime("project-1", {"id": "train-run", "status": "queued"})\n    assert job["status"] == "running"\n    assert job["progress_percent"] == 18\n    assert job["current_item"] == "epoch 2/10"\n    assert job["task_worker_id"] == "a800-worker-01"\n    assert job["task_lease_expires_at"]\n''', encoding='utf-8')

print('training unified task truth patch prepared')
