from pathlib import Path

CACHE = Path("platform_core/resource_discovery/cache.py")
TASKS = Path("platform_core/resource_discovery/tasks.py")

cache = CACHE.read_text(encoding="utf-8")
tasks = TASKS.read_text(encoding="utf-8")

old_import = "from typing import Any, Iterable, Iterator, Mapping, Sequence\n"
new_import = old_import + "\nfrom filelock import FileLock\n"
if cache.count(old_import) != 1 or "from filelock import FileLock" in cache:
    raise SystemExit("cache import anchor changed")
cache = cache.replace(old_import, new_import, 1)

schema_anchor = "\n_KIND_ALIASES = {\n"
if cache.count(schema_anchor) != 1:
    raise SystemExit("schema version anchor changed")
cache = cache.replace(schema_anchor, "\n_SCHEMA_VERSION = 1\n_INIT_LOCK_TIMEOUT = 30\n" + schema_anchor, 1)

old_block = '''    def __init__(self, path: str | Path) -> None:\n        self.path = Path(path).expanduser()\n        self.path.parent.mkdir(parents=True, exist_ok=True)\n        with closing(self._connect()) as database:\n            database.executescript(_SCHEMA)\n            database.executemany(\n                "INSERT OR IGNORE INTO cache_meta(cache_kind) VALUES (?)",\n                (("environment",), ("models",)),\n            )\n\n    def _connect(self) -> sqlite3.Connection:\n        database = sqlite3.connect(self.path, timeout=30, isolation_level=None)\n        try:\n            database.row_factory = sqlite3.Row\n            database.execute("PRAGMA journal_mode=WAL")\n            database.execute("PRAGMA foreign_keys=ON")\n            database.execute("PRAGMA busy_timeout=30000")\n            return database\n        except BaseException:\n            database.close()\n            raise\n\n    @contextmanager\n    def _transaction(self) -> Iterator[sqlite3.Connection]:\n        with closing(self._connect()) as database:\n            database.execute("BEGIN IMMEDIATE")\n            try:\n                yield database\n                database.execute("COMMIT")\n            except BaseException:\n                database.execute("ROLLBACK")\n                raise\n'''
new_block = '''    def __init__(self, path: str | Path) -> None:\n        self.path = Path(path).expanduser()\n        self.path.parent.mkdir(parents=True, exist_ok=True)\n        self._initialize()\n\n    def _connect(self) -> sqlite3.Connection:\n        database = sqlite3.connect(self.path, timeout=30, isolation_level=None)\n        try:\n            database.row_factory = sqlite3.Row\n            database.execute("PRAGMA foreign_keys=ON")\n            database.execute("PRAGMA busy_timeout=30000")\n            return database\n        except BaseException:\n            database.close()\n            raise\n\n    def _initialize(self) -> None:\n        # journal_mode is persistent database state. Reasserting WAL on every\n        # connection can participate in startup lock races, so schema/WAL setup\n        # has one cross-process owner and is version-gated.\n        lock = FileLock(f"{self.path}.init.lock", timeout=_INIT_LOCK_TIMEOUT)\n        with lock:\n            with closing(self._connect()) as database:\n                version = int(database.execute("PRAGMA user_version").fetchone()[0])\n                if version > _SCHEMA_VERSION:\n                    raise RuntimeError(\n                        f"resource discovery cache schema {version} is newer than supported {_SCHEMA_VERSION}"\n                    )\n                if version == _SCHEMA_VERSION:\n                    return\n                mode = str(database.execute("PRAGMA journal_mode").fetchone()[0]).lower()\n                if mode != "wal":\n                    mode = str(database.execute("PRAGMA journal_mode=WAL").fetchone()[0]).lower()\n                if mode != "wal":\n                    raise RuntimeError(f"resource discovery cache requires WAL mode, got {mode}")\n                database.executescript(_SCHEMA)\n                database.executemany(\n                    "INSERT OR IGNORE INTO cache_meta(cache_kind) VALUES (?)",\n                    (("environment",), ("models",)),\n                )\n                database.execute(f"PRAGMA user_version={_SCHEMA_VERSION}")\n\n    @contextmanager\n    def _transaction(self) -> Iterator[sqlite3.Connection]:\n        with closing(self._connect()) as database:\n            database.execute("BEGIN IMMEDIATE")\n            try:\n                yield database\n            except BaseException:\n                if database.in_transaction:\n                    database.rollback()\n                raise\n            else:\n                database.commit()\n'''
if cache.count(old_block) != 1:
    raise SystemExit(f"DiscoveryCache lifecycle block changed; matches={cache.count(old_block)}")
cache = cache.replace(old_block, new_block, 1)

if 'database.execute("PRAGMA journal_mode=WAL")' in new_block.split("def _initialize", 1)[0]:
    raise SystemExit("WAL pragma accidentally remains in ordinary connection setup")

old_tasks_import = "import sqlite3\nfrom dataclasses import replace\n"
new_tasks_import = "import sqlite3\nfrom contextlib import closing\nfrom dataclasses import replace\n"
if tasks.count(old_tasks_import) != 1:
    raise SystemExit("tasks import anchor changed")
tasks = tasks.replace(old_tasks_import, new_tasks_import, 1)

old_manifest = '''    def __init__(self, path: Path) -> None:\n        self.path = path\n        self.path.parent.mkdir(parents=True, exist_ok=True)\n        self._pending: list[dict[str, Any]] = []\n        with self._connect() as database:\n            database.execute(\n                "CREATE TABLE IF NOT EXISTS models "\n                "(path_key TEXT PRIMARY KEY, payload_json TEXT NOT NULL)"\n            )\n\n    def _connect(self) -> sqlite3.Connection:\n        database = sqlite3.connect(self.path, timeout=30)\n        database.execute("PRAGMA busy_timeout=30000")\n        return database\n\n    def reset(self) -> None:\n        with self._connect() as database:\n            database.execute("DELETE FROM models")\n\n    def add(self, row: Mapping[str, Any]) -> None:\n        self._pending.append(dict(row))\n        if len(self._pending) >= _MODEL_BATCH_SIZE:\n            self.flush()\n\n    def flush(self) -> None:\n        if not self._pending:\n            return\n        rows = self._pending\n        self._pending = []\n        with self._connect() as database:\n            database.executemany(\n                "INSERT OR REPLACE INTO models(path_key,payload_json) VALUES (?,?)",\n                (\n                    (\n                        _path_key(str(row.get("path") or "")),\n                        json.dumps(row, ensure_ascii=False, sort_keys=True),\n                    )\n                    for row in rows\n                ),\n            )\n\n    def count(self) -> int:\n        self.flush()\n        with self._connect() as database:\n            return int(database.execute("SELECT COUNT(*) FROM models").fetchone()[0])\n\n    def rows(self) -> Iterable[dict[str, Any]]:\n        self.flush()\n        with self._connect() as database:\n            cursor = database.execute(\n                "SELECT payload_json FROM models ORDER BY path_key"\n            )\n            for row in cursor:\n                yield dict(json.loads(row[0]))\n'''
new_manifest = '''    def __init__(self, path: Path) -> None:\n        self.path = path\n        self.path.parent.mkdir(parents=True, exist_ok=True)\n        self._pending: list[dict[str, Any]] = []\n        with closing(self._connect()) as database:\n            with database:\n                database.execute(\n                    "CREATE TABLE IF NOT EXISTS models "\n                    "(path_key TEXT PRIMARY KEY, payload_json TEXT NOT NULL)"\n                )\n\n    def _connect(self) -> sqlite3.Connection:\n        database = sqlite3.connect(self.path, timeout=30)\n        database.execute("PRAGMA busy_timeout=30000")\n        return database\n\n    def reset(self) -> None:\n        with closing(self._connect()) as database:\n            with database:\n                database.execute("DELETE FROM models")\n\n    def add(self, row: Mapping[str, Any]) -> None:\n        self._pending.append(dict(row))\n        if len(self._pending) >= _MODEL_BATCH_SIZE:\n            self.flush()\n\n    def flush(self) -> None:\n        if not self._pending:\n            return\n        rows = self._pending\n        self._pending = []\n        with closing(self._connect()) as database:\n            with database:\n                database.executemany(\n                    "INSERT OR REPLACE INTO models(path_key,payload_json) VALUES (?,?)",\n                    (\n                        (\n                            _path_key(str(row.get("path") or "")),\n                            json.dumps(row, ensure_ascii=False, sort_keys=True),\n                        )\n                        for row in rows\n                    ),\n                )\n\n    def count(self) -> int:\n        self.flush()\n        with closing(self._connect()) as database:\n            return int(database.execute("SELECT COUNT(*) FROM models").fetchone()[0])\n\n    def rows(self) -> Iterable[dict[str, Any]]:\n        self.flush()\n        with closing(self._connect()) as database:\n            with closing(database.execute(\n                "SELECT payload_json FROM models ORDER BY path_key"\n            )) as cursor:\n                for row in cursor:\n                    yield dict(json.loads(row[0]))\n'''
if tasks.count(old_manifest) != 1:
    raise SystemExit(f"ModelManifest lifecycle block changed; matches={tasks.count(old_manifest)}")
tasks = tasks.replace(old_manifest, new_manifest, 1)

CACHE.write_text(cache, encoding="utf-8")
TASKS.write_text(tasks, encoding="utf-8")
print("Resource Discovery SQLite lifecycle migration applied")
